### ISSUE TITLE
BUG: when forced to switch tasks/apps, freeciv crashes

### ISSUE THREAD

**Issue by andwan0** [zielmicha/freeciv-android#14]
When I play, then all of a sudden my alarm goes off, or some other notification (like special calendar event), or even if I accidently press the BACK/HOME buttons... 
then when I go back into FreeCiv, it's shrunk to a quarter of the screen... and the rest of the screen is garbled.... and it's also non-responsive by this time... so I have to forcibly restart it.

**Comment by javaxubuntu** [comment]
In version 2.6.0 it almost never happen, and if it happen, switching again between apps fixes the problem.
