### ISSUE TITLE
How to add a ruleset or modify option like the desktop application ?

### ISSUE THREAD

**Issue by mathieuaubert** [zielmicha/freeciv-android#21]
Hi,

I'm writing to ask if it was possible to add a ruleset on the android application?
Or can I manually change the "killstack" option to false ? 

Thank you for your work.

**Comment by javaxubuntu** [comment]
This is currently not possible to add new rulesets nor tilesets, but you can change any server option before game start with the "server command" button, for example:
/set killstack disabled

**Comment by JAmathieu** [comment]
Thank you very much for your answer

I'm sorry but I can't find the server command button on the Android application. I have the latest version of August 4, 2018.

**Comment by mathieuaubert** [comment]
Thank you very much for your answer

I'm sorry but I can't find the server command button on the Android application. I have the latest version of August 4, 2018.

**Comment by Ant247** [comment]
Start a new random game.
Server Command is 5 item on the menu just below difficulty.

**Comment by JAmathieu** [comment]
Okay, I found it.
Thank you very much

**Comment by mathieuaubert** [comment]
Okay, I found it.
Thank you very much
